PreCommit:
  Spec:
    enabled: true
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

PostCheckout:
  ALL:
    enabled: false

PostCommit:
  ALL:
    enabled: false

PrePush:
  RSpec:
    enabled: true
