##
# Bug with Travis rubocop and rainbow gem
# resolve:
# https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431898694
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - '**/tmp/**/*'
    - '**/script/**/*'
    - Rakefile
    - 'bin/*'
  UseCache: true
  SuggestExtensions: false
  NewCops: enable

Metrics/LineLength:
  Max: 120
  AllowedPatterns: ['\s*\#\s.*$']
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'luna_park.gemspec'

Style/AsciiComments:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/Attr:
  Enabled: false

# TODO: убрать/изменить правило
Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: io, id, to, by, on, in, at, ip, db, pk, fk

# TODO: поговорить с Филиппом про attr
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/EmptyClass:
  Enabled: false

# TODO: поговорить с Филиппом про attr
Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

