##
# Bug with Travis rubocop and rainbow gem
# resolve:
# https://github.com/rubocop-hq/rubocop/issues/6398#issuecomment-431898694
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/tmp/**/*'
    - '**/script/**/*'
    - Rakefile
    - 'bin/*'
  UseCache: true

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\s*\#\s.*$']
  Exclude:
    - 'spec/**/*'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'luna_park.gemspec'

Style/AsciiComments:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Style/Attr:
  Enabled: false

# TODO: убрать/изменить правило
Style/Documentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames: io, id, to, by, on, in, at, ip, db, pk, fk
